import R6.PaperR16LowerFactorPreprocessing

/-!
# Canonical role partition for a finite independent-factor scope list

Occurrence indices are not identified by equal scopes. The relation generated
by co-occurrence in a scope is the two-section connectivity relation. Core
roles are those connected to a boundary, unused middle roles read no scope,
and the remaining used roles are detached.
-/

noncomputable section

namespace GraphMatrixReplica.PaperR16

/-- The raw finite shape before preprocessing. Two occurrences may have the
same scope; their indices remain distinct. -/
structure RawFactorShape (W E : Type*) where
  size : W → ℕ
  leftBoundary : Finset W
  rightBoundary : Finset W
  scope : E → Finset W
  scope_nonempty : ∀ e, (scope e).Nonempty

namespace RawFactorShape

variable {W E : Type*} [Fintype W] [Fintype E] [DecidableEq W]
variable (S : RawFactorShape W E)

def boundary : Finset W := S.leftBoundary ∪ S.rightBoundary

/-- One step of the factor two-section graph. The occurrence is explicit. -/
def CoScope (u v : W) : Prop :=
  ∃ e : E, u ∈ S.scope e ∧ v ∈ S.scope e

/-- Finite-walk connectivity generated by whole-factor co-occurrence. -/
inductive Connected : W → W → Prop
  | refl (w : W) : Connected w w
  | edge {u v : W} (h : S.CoScope u v) : Connected u v
  | trans {u v z : W} (h₁ : Connected u v) (h₂ : Connected v z) :
      Connected u z

theorem coScope_symm {u v : W} (h : S.CoScope u v) : S.CoScope v u := by
  rcases h with ⟨e, hu, hv⟩
  exact ⟨e, hv, hu⟩

theorem connected_symm {u v : W} (h : S.Connected u v) :
    S.Connected v u := by
  induction h with
  | refl w => exact Connected.refl w
  | edge h => exact Connected.edge (S.coScope_symm h)
  | trans h₁ h₂ ih₁ ih₂ => exact Connected.trans ih₂ ih₁

/-- Every pair of roles in one occurrence's scope belongs to one component. -/
theorem connected_of_mem_scope (e : E) {u v : W}
    (hu : u ∈ S.scope e) (hv : v ∈ S.scope e) :
    S.Connected u v :=
  Connected.edge ⟨e, hu, hv⟩

def UsedRole (w : W) : Prop := ∃ e : E, w ∈ S.scope e

/-- Boundary roles, even if no factor uses them, stay in the core. -/
def CoreRole (w : W) : Prop :=
  ∃ b : W, b ∈ S.boundary ∧ S.Connected w b

/-- Exactly the roles that contribute a pure dimension scalar. -/
def UnusedMiddleRole (w : W) : Prop :=
  ¬ S.UsedRole w ∧ w ∉ S.boundary

/-- Used roles in factor components disjoint from both boundaries. -/
def DetachedRole (w : W) : Prop :=
  S.UsedRole w ∧ ¬ S.CoreRole w

theorem core_of_mem_boundary {w : W} (hw : w ∈ S.boundary) :
    S.CoreRole w := ⟨w, hw, Connected.refl w⟩

theorem core_of_connected {u v : W} (hu : S.CoreRole u)
    (h : S.Connected v u) : S.CoreRole v := by
  rcases hu with ⟨b, hb, hub⟩
  exact ⟨b, hb, Connected.trans h hub⟩

theorem core_iff_connected_boundary (w : W) :
    S.CoreRole w ↔ ∃ b ∈ S.boundary, S.Connected w b := Iff.rfl

/-- An unused role has no outgoing co-scope edge, so its only reachable role
is itself. -/
theorem connected_eq_of_not_used {u v : W} (h : S.Connected u v)
    (hu : ¬ S.UsedRole u) : u = v := by
  induction h with
  | refl _ => rfl
  | edge h =>
      rcases h with ⟨e, hue, _⟩
      exact False.elim (hu ⟨e, hue⟩)
  | trans h₁ h₂ ih₁ ih₂ =>
      have hEq := ih₁ hu
      have hUnusedNext := hEq ▸ hu
      exact hEq.trans (ih₂ hUnusedNext)

theorem role_partition (w : W) :
    S.CoreRole w ∨ S.UnusedMiddleRole w ∨ S.DetachedRole w := by
  classical
  by_cases hc : S.CoreRole w
  · exact Or.inl hc
  · by_cases hu : S.UsedRole w
    · exact Or.inr (Or.inr ⟨hu, hc⟩)
    · exact Or.inr (Or.inl ⟨hu, fun hb => hc (S.core_of_mem_boundary hb)⟩)

theorem core_not_unused {w : W} (hc : S.CoreRole w) :
    ¬ S.UnusedMiddleRole w := by
  intro hu
  rcases hc with ⟨b, hb, hwb⟩
  have hEq : w = b := S.connected_eq_of_not_used hwb hu.1
  exact hu.2 (hEq ▸ hb)

theorem core_not_detached {w : W} (hc : S.CoreRole w) :
    ¬ S.DetachedRole w := fun hd => hd.2 hc

theorem unused_not_detached {w : W} (hu : S.UnusedMiddleRole w) :
    ¬ S.DetachedRole w := fun hd => hu.1 hd.1

theorem scope_used (e : E) {w : W} (hw : w ∈ S.scope e) :
    S.UsedRole w := ⟨e, hw⟩

theorem scope_core_closed (e : E) {u v : W}
    (hu : u ∈ S.scope e) (hv : v ∈ S.scope e)
    (hcore : S.CoreRole u) : S.CoreRole v :=
  S.core_of_connected hcore (S.connected_of_mem_scope e hv hu)

theorem scope_detached_closed (e : E) {u v : W}
    (hu : u ∈ S.scope e) (hv : v ∈ S.scope e)
    (hdet : S.DetachedRole u) : S.DetachedRole v := by
  refine ⟨S.scope_used e hv, ?_⟩
  intro hc
  exact hdet.2 (S.scope_core_closed e hv hu hc)

/-- A factor occurrence cannot straddle the core and a detached component. -/
theorem scope_core_or_detached (e : E) :
    (∀ w ∈ S.scope e, S.CoreRole w) ∨
      (∀ w ∈ S.scope e, S.DetachedRole w) := by
  classical
  obtain ⟨u, hu⟩ := S.scope_nonempty e
  by_cases hc : S.CoreRole u
  · exact Or.inl (fun w hw => S.scope_core_closed e hu hw hc)
  · have hd : S.DetachedRole u := ⟨S.scope_used e hu, hc⟩
    exact Or.inr (fun w hw => S.scope_detached_closed e hu hw hd)

/-- An occurrence's whole scope lies in one connected component. -/
theorem scope_one_component (e : E) {u v : W}
    (hu : u ∈ S.scope e) (hv : v ∈ S.scope e) :
    S.Connected u v := S.connected_of_mem_scope e hu hv

def coreRoles : Finset W := by
  classical exact Finset.univ.filter S.CoreRole
def unusedMiddleRoles : Finset W := by
  classical exact Finset.univ.filter S.UnusedMiddleRole
def detachedRoles : Finset W := by
  classical exact Finset.univ.filter S.DetachedRole

@[simp] theorem mem_coreRoles {w : W} :
    w ∈ S.coreRoles ↔ S.CoreRole w := by simp [coreRoles]

@[simp] theorem mem_unusedMiddleRoles {w : W} :
    w ∈ S.unusedMiddleRoles ↔ S.UnusedMiddleRole w := by
  simp [unusedMiddleRoles]

@[simp] theorem mem_detachedRoles {w : W} :
    w ∈ S.detachedRoles ↔ S.DetachedRole w := by
  simp [detachedRoles]

theorem role_finset_cover (w : W) :
    w ∈ S.coreRoles ∨ w ∈ S.unusedMiddleRoles ∨
      w ∈ S.detachedRoles := by
  simpa using S.role_partition w

theorem core_unused_disjoint :
    Disjoint S.coreRoles S.unusedMiddleRoles := by
  apply Finset.disjoint_left.mpr
  intro w hc hu
  exact S.core_not_unused (S.mem_coreRoles.mp hc)
    (S.mem_unusedMiddleRoles.mp hu)

theorem core_detached_disjoint :
    Disjoint S.coreRoles S.detachedRoles := by
  apply Finset.disjoint_left.mpr
  intro w hc hd
  exact S.core_not_detached (S.mem_coreRoles.mp hc)
    (S.mem_detachedRoles.mp hd)

theorem unused_detached_disjoint :
    Disjoint S.unusedMiddleRoles S.detachedRoles := by
  apply Finset.disjoint_left.mpr
  intro w hu hd
  exact S.unused_not_detached (S.mem_unusedMiddleRoles.mp hu)
    (S.mem_detachedRoles.mp hd)

theorem role_finset_union :
    S.coreRoles ∪ S.unusedMiddleRoles ∪ S.detachedRoles =
      Finset.univ := by
  apply Finset.eq_univ_iff_forall.mpr
  intro w
  rcases S.role_finset_cover w with hc | hu | hd
  · exact Finset.mem_union.mpr (Or.inl (Finset.mem_union.mpr (Or.inl hc)))
  · exact Finset.mem_union.mpr (Or.inl (Finset.mem_union.mpr (Or.inr hu)))
  · exact Finset.mem_union.mpr (Or.inr hd)

/-- Two-section connectivity as an equivalence relation. -/
def componentSetoid : Setoid W where
  r := S.Connected
  iseqv := ⟨fun w => Connected.refl w,
    fun {_ _} h => S.connected_symm h,
    fun {_ _ _} h₁ h₂ => Connected.trans h₁ h₂⟩

def Component := Quotient S.componentSetoid

def component (w : W) : S.Component := Quotient.mk S.componentSetoid w

theorem component_eq_of_connected {u v : W}
    (h : S.Connected u v) : S.component u = S.component v :=
  Quotient.sound h

theorem connected_of_component_eq {u v : W}
    (h : S.component u = S.component v) : S.Connected u v :=
  Quotient.exact h

theorem component_scope_eq (e : E) {u v : W}
    (hu : u ∈ S.scope e) (hv : v ∈ S.scope e) :
    S.component u = S.component v :=
  S.component_eq_of_connected (S.scope_one_component e hu hv)

/-- Once one member of a connected component is used by a factor, all of
its members are used. The only unused components are isolated singletons. -/
theorem used_of_connected {u v : W} (hu : S.UsedRole u)
    (h : S.Connected u v) : S.UsedRole v := by
  by_contra hv
  have hEq : v = u :=
    S.connected_eq_of_not_used (S.connected_symm h) hv
  subst v
  exact hv hu

theorem detached_of_connected {u v : W} (hu : S.DetachedRole u)
    (h : S.Connected u v) : S.DetachedRole v := by
  refine ⟨S.used_of_connected hu.1 h, ?_⟩
  intro hc
  exact hu.2 (S.core_of_connected hc h)

/-- A detached component is an equivalence class that actually contains a
detached role. Components consisting of unused middle roles are excluded. -/
def DetachedComponent :=
  {c : S.Component // ∃ w : W, S.DetachedRole w ∧ S.component w = c}

def detachedComponentOfRole (w : W) (hw : S.DetachedRole w) :
    S.DetachedComponent :=
  ⟨S.component w, ⟨w, hw, rfl⟩⟩

def detachedComponentRoles (j : S.DetachedComponent) : Finset W := by
  classical
  exact Finset.univ.filter (fun w => S.DetachedRole w ∧ S.component w = j.1)

@[simp] theorem mem_detachedComponentRoles {j : S.DetachedComponent}
    {w : W} : w ∈ S.detachedComponentRoles j ↔
      S.DetachedRole w ∧ S.component w = j.1 := by
  simp [detachedComponentRoles]

theorem detached_role_unique_component {w : W} (hw : S.DetachedRole w) :
    ∃! j : S.DetachedComponent, w ∈ S.detachedComponentRoles j := by
  refine ⟨S.detachedComponentOfRole w hw, ?_, ?_⟩
  · exact S.mem_detachedComponentRoles.mpr ⟨hw, rfl⟩
  · intro j hj
    apply Subtype.ext
    exact (S.mem_detachedComponentRoles.mp hj).2.symm

theorem detached_components_disjoint {j k : S.DetachedComponent}
    (hjk : j ≠ k) :
    Disjoint (S.detachedComponentRoles j) (S.detachedComponentRoles k) := by
  apply Finset.disjoint_left.mpr
  intro w hwj hwk
  apply hjk
  apply Subtype.ext
  calc
    j.1 = S.component w := (S.mem_detachedComponentRoles.mp hwj).2.symm
    _ = k.1 := (S.mem_detachedComponentRoles.mp hwk).2

/-- Raw occurrence classification by the canonical boundary-connected
component partition. -/
def CoreOccurrence (e : E) : Prop :=
  ∀ w ∈ S.scope e, S.CoreRole w

def DetachedOccurrence (j : S.DetachedComponent) (e : E) : Prop :=
  ∀ w ∈ S.scope e, w ∈ S.detachedComponentRoles j

theorem occurrence_core_or_detached (e : E) :
    S.CoreOccurrence e ∨
      ∃! j : S.DetachedComponent, S.DetachedOccurrence j e := by
  classical
  rcases S.scope_core_or_detached e with hc | hd
  · exact Or.inl hc
  · obtain ⟨u, hu⟩ := S.scope_nonempty e
    let j := S.detachedComponentOfRole u (hd u hu)
    right
    refine ⟨j, ?_, ?_⟩
    · intro w hw
      have hComp := S.component_scope_eq e hw hu
      exact S.mem_detachedComponentRoles.mpr
        ⟨hd w hw, by simpa [j, detachedComponentOfRole] using hComp⟩
    · intro k hk
      apply Subtype.ext
      have hku := (S.mem_detachedComponentRoles.mp (hk u hu)).2
      exact by simpa [j, detachedComponentOfRole] using hku.symm

theorem core_occurrence_not_detached (e : E)
    (hc : S.CoreOccurrence e) (j : S.DetachedComponent) :
    ¬ S.DetachedOccurrence j e := by
  intro hd
  obtain ⟨u, hu⟩ := S.scope_nonempty e
  exact S.core_not_detached (hc u hu)
    (S.mem_detachedComponentRoles.mp (hd u hu)).1

/-- Canonical types feeding the typed preprocessing theorem. -/
abbrev CanonicalCore := {w : W // S.CoreRole w}
abbrev CanonicalUnused := {w : W // S.UnusedMiddleRole w}
abbrev CanonicalDetached (j : S.DetachedComponent) :=
  {w : W // w ∈ S.detachedComponentRoles j}
abbrev CanonicalCoreOccurrence := {e : E // S.CoreOccurrence e}
abbrev CanonicalDetachedOccurrence (j : S.DetachedComponent) :=
  {e : E // S.DetachedOccurrence j e}

/-- This construction has no externally supplied partition hypothesis. Its
scope fields are the actual raw occurrence scopes restricted to the uniquely
determined component role types. -/
def canonicalPreprocessedShape :
    PreprocessedFactorShape S.CanonicalCore S.CanonicalUnused
      S.DetachedComponent S.CanonicalDetached
      S.CanonicalCoreOccurrence S.CanonicalDetachedOccurrence := by
  classical
  letI : Fintype S.CanonicalCore := Fintype.ofFinite _
  letI : ∀ j : S.DetachedComponent, Fintype (S.CanonicalDetached j) :=
    fun _ => Fintype.ofFinite _
  refine {
    coreSize := fun c => S.size c.1
    unusedSize := fun u => S.size u.1
    detachedSize := fun _ d => S.size d.1
    leftBoundary := Finset.univ.filter (fun c => c.1 ∈ S.leftBoundary)
    rightBoundary := Finset.univ.filter (fun c => c.1 ∈ S.rightBoundary)
    coreScope := fun e => Finset.univ.filter (fun c => c.1 ∈ S.scope e.1)
    coreScope_nonempty := ?_
    detachedScope := fun j e =>
      Finset.univ.filter (fun d => d.1 ∈ S.scope e.1)
    detachedScope_nonempty := ?_ }
  · intro e
    obtain ⟨w, hw⟩ := S.scope_nonempty e.1
    exact ⟨⟨w, e.2 w hw⟩, by simp [hw]⟩
  · intro j e
    obtain ⟨w, hw⟩ := S.scope_nonempty e.1
    exact ⟨⟨w, e.2 w hw⟩, by simp [hw]⟩

#print axioms RawFactorShape.role_finset_union
#print axioms RawFactorShape.scope_core_or_detached
#print axioms RawFactorShape.component_scope_eq
#print axioms RawFactorShape.occurrence_core_or_detached
#print axioms RawFactorShape.canonicalPreprocessedShape

end RawFactorShape
end GraphMatrixReplica.PaperR16
